  -  name: Installing NFS Server.
     yum:
       name: nfs-utils
       state: installed
  -  name: Ensure nfs-server is running.
     service:
       name: nfs-server
       state: started
       enabled: yes
