---
  - name: playbook_before_roles
    hosts: webservers
    become: yes
    tasks: 
      - name: download nfs
        yum: 
          name: nfs-utils
          state: latest
      - name: ensure it is running and boot persistent
        service:
          name: nfs
          state: started
          enabled: true
        become: true
  - hosts: dbservers
    become: yes
    tasks:
      - name: copy file from master
        copy:
          src: /etc/ansible/test/test.txt
          dest: /etc/ansible/test/test.txt
      - name: create new user named saka
        user: 
          name: saka
          state: present
  - hosts: testservers
    become: yes
    tasks:
      - name: update installed packages
        command: yum update -y
      - name: cron task
        cron:
          name: "cron update"
          special_time: daily
          job:  yum update -y
      - name: download httpd
        yum:
          name: httpd
          state: latest 
      - name: change line in httpd.conf file
        lineinfile: 
          path: /etc/httpd/conf/httpd.conf
          regexp: "ServerAdmin root@localhost"
          line: ServerAdmin saka@sakasama 
